[build]
# use zig cc to fix missing x86_64-unknown-linux-gnu-gcc linker errors
zig = true

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "apt-get update && apt-get upgrade",
    "apt-get install libavahi-client-dev avahi-daemon -y"
]