[package]
name = "browse-example"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
qmulti = { path="../.." }
tokio = { version="1.35", features=["full"] }
